     <section class="content">          <div class="row">            <div class="col-md-12">			                 <div class="box box-info">                <div class="box-header with-border">                  <h3 class="box-title">Danh Sách Tin Tức</h3>                  <div class="box-tools pull-right">				   <button type="submit" class="btn btn-info " onclick='window.location.href = "index.php?act=ads&mode=add"'>Thêm ADS Mới</button>                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>                  </div>                </div><!-- /.box-header -->	                <div class="box-body">				<section class="panel panel-default">                <div class="table-responsive">				<form name=media_list method=post action='index.php?act=list-ads&mode=list-ads' onSubmit="return check_checkbox();">                  <table class="table table-striped b-t b-light">                    <thead>                      <tr>                                               <th class="th-sortable" data-toggle="class">#</th>                        <th>ID</th>                        <th>Tên QC</th>                        <th>Vị trí(key)</th>						  <th>Tình trạng</th>                        </tr>                      </thead>                      <tbody>
<?php
	$arr = $mlivedb->query(" adv_id ,adv_name ,adv_vitri , adv_status,adv_stt ","adv"," adv_id != 0 ORDER BY adv_stt ASC");
	for($i=0;$i<count($arr);$i++) {
		if($arr[$i][3]==0)	$status	=	'<a href="index.php?act=ads&mode=status&status=1&id='.$arr[$i][0].'"><font color="green">Mở</font></a>';
		if($arr[$i][3]==1)	$status	=	'<a class=\"no\" href="index.php?act=ads&mode=status&status=0&id='.$arr[$i][0].'"><font color="red">Đóng</font></a>';
	?>
        <tr>		 <td><input class=checkbox type=checkbox id=checkbox onclick=docheckone() name=checkbox[] value=<?php  echo $arr[$i][0];?>></td> <td>#<?=$arr[$i][0];?></td>
        <td><a href="index.php?act=ads&mode=edit&id=<?=$arr[$i][0];?>" title="Edit"><b><?=$arr[$i][1];?></b></a></td>  <td><?=$arr[$i][2];?></td> <td><?=$status;?></td><td align=right><a href="index.php?act=ads&del_id=<?=$arr[$i][0];?>" title="Xóa"  onClick="return ask()" title="Xóa" ><button type="button" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></button></a></td>						
        </tr>
       <?php } ?></table>                </div>				 <footer class="panel-footer">                  <div class="row">                    <div class="col-sm-4 hidden-xs">               	 <div><select name="selected_option" class="input-sm form-control input-s-sm inline v-middle">         <option value="del">Xóa</option> </select> <input class="btn btn-sm btn-default" type="submit" name="do" value="Apply"> </div>                        </form>					                      </div>                                    <thead> <ul class="pagination pagination-sm no-margin pull-right"><?php  echo $phan_trang;?></ul>                  </div>                </footer>              </section>            </div><!-- /.col-->         </div></div> </div><!-- ./row -->        </section><!-- /.content -->
<script>
function ask(){
	if (confirm("Bạn có muốn xóa quảng cáo này ?")) return true;
	return false ;
}
</script><?php if ($_POST['do']) {	$arr = $_POST['checkbox'];	if (!count($arr)) die('Lỗi');	if ($_POST['selected_option'] == 'del') {		$in_sql = implode(',',$arr);		mysqli_query($link_music,"DELETE FROM table_adv WHERE adv_id IN (".$in_sql.")");		mss ("Xóa thành công ","index.php?act=list-ads&mode=list-ads");	}			exit();}?>